// Code generated by mockery. DO NOT EDIT.

package mocks

import (
	context "context"

	repository "github.com/Foga2H/ya-go-url-shortener/internal/repository"
	mock "github.com/stretchr/testify/mock"
)

// StorageRepo is an autogenerated mock type for the StorageRepo type
type StorageRepo struct {
	mock.Mock
}

type StorageRepo_Expecter struct {
	mock *mock.Mock
}

func (_m *StorageRepo) EXPECT() *StorageRepo_Expecter {
	return &StorageRepo_Expecter{mock: &_m.Mock}
}

// BatchDelete provides a mock function with given fields: ctx, userID, links
func (_m *StorageRepo) BatchDelete(ctx context.Context, userID string, links []string) error {
	ret := _m.Called(ctx, userID, links)

	if len(ret) == 0 {
		panic("no return value specified for BatchDelete")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, string, []string) error); ok {
		r0 = rf(ctx, userID, links)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// StorageRepo_BatchDelete_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'BatchDelete'
type StorageRepo_BatchDelete_Call struct {
	*mock.Call
}

// BatchDelete is a helper method to define mock.On call
//   - ctx context.Context
//   - userID string
//   - links []string
func (_e *StorageRepo_Expecter) BatchDelete(ctx interface{}, userID interface{}, links interface{}) *StorageRepo_BatchDelete_Call {
	return &StorageRepo_BatchDelete_Call{Call: _e.mock.On("BatchDelete", ctx, userID, links)}
}

func (_c *StorageRepo_BatchDelete_Call) Run(run func(ctx context.Context, userID string, links []string)) *StorageRepo_BatchDelete_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string), args[2].([]string))
	})
	return _c
}

func (_c *StorageRepo_BatchDelete_Call) Return(_a0 error) *StorageRepo_BatchDelete_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *StorageRepo_BatchDelete_Call) RunAndReturn(run func(context.Context, string, []string) error) *StorageRepo_BatchDelete_Call {
	_c.Call.Return(run)
	return _c
}

// Get provides a mock function with given fields: ctx, key
func (_m *StorageRepo) Get(ctx context.Context, key string) (repository.UserLink, bool) {
	ret := _m.Called(ctx, key)

	if len(ret) == 0 {
		panic("no return value specified for Get")
	}

	var r0 repository.UserLink
	var r1 bool
	if rf, ok := ret.Get(0).(func(context.Context, string) (repository.UserLink, bool)); ok {
		return rf(ctx, key)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string) repository.UserLink); ok {
		r0 = rf(ctx, key)
	} else {
		r0 = ret.Get(0).(repository.UserLink)
	}

	if rf, ok := ret.Get(1).(func(context.Context, string) bool); ok {
		r1 = rf(ctx, key)
	} else {
		r1 = ret.Get(1).(bool)
	}

	return r0, r1
}

// StorageRepo_Get_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Get'
type StorageRepo_Get_Call struct {
	*mock.Call
}

// Get is a helper method to define mock.On call
//   - ctx context.Context
//   - key string
func (_e *StorageRepo_Expecter) Get(ctx interface{}, key interface{}) *StorageRepo_Get_Call {
	return &StorageRepo_Get_Call{Call: _e.mock.On("Get", ctx, key)}
}

func (_c *StorageRepo_Get_Call) Run(run func(ctx context.Context, key string)) *StorageRepo_Get_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string))
	})
	return _c
}

func (_c *StorageRepo_Get_Call) Return(_a0 repository.UserLink, _a1 bool) *StorageRepo_Get_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *StorageRepo_Get_Call) RunAndReturn(run func(context.Context, string) (repository.UserLink, bool)) *StorageRepo_Get_Call {
	_c.Call.Return(run)
	return _c
}

// GetByUserID provides a mock function with given fields: ctx, userID
func (_m *StorageRepo) GetByUserID(ctx context.Context, userID string) ([]repository.UserLink, error) {
	ret := _m.Called(ctx, userID)

	if len(ret) == 0 {
		panic("no return value specified for GetByUserID")
	}

	var r0 []repository.UserLink
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string) ([]repository.UserLink, error)); ok {
		return rf(ctx, userID)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string) []repository.UserLink); ok {
		r0 = rf(ctx, userID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]repository.UserLink)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = rf(ctx, userID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// StorageRepo_GetByUserID_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetByUserID'
type StorageRepo_GetByUserID_Call struct {
	*mock.Call
}

// GetByUserID is a helper method to define mock.On call
//   - ctx context.Context
//   - userID string
func (_e *StorageRepo_Expecter) GetByUserID(ctx interface{}, userID interface{}) *StorageRepo_GetByUserID_Call {
	return &StorageRepo_GetByUserID_Call{Call: _e.mock.On("GetByUserID", ctx, userID)}
}

func (_c *StorageRepo_GetByUserID_Call) Run(run func(ctx context.Context, userID string)) *StorageRepo_GetByUserID_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string))
	})
	return _c
}

func (_c *StorageRepo_GetByUserID_Call) Return(_a0 []repository.UserLink, _a1 error) *StorageRepo_GetByUserID_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *StorageRepo_GetByUserID_Call) RunAndReturn(run func(context.Context, string) ([]repository.UserLink, error)) *StorageRepo_GetByUserID_Call {
	_c.Call.Return(run)
	return _c
}

// Set provides a mock function with given fields: ctx, userID, key, value
func (_m *StorageRepo) Set(ctx context.Context, userID string, key string, value string) (string, error) {
	ret := _m.Called(ctx, userID, key, value)

	if len(ret) == 0 {
		panic("no return value specified for Set")
	}

	var r0 string
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string, string, string) (string, error)); ok {
		return rf(ctx, userID, key, value)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string, string, string) string); ok {
		r0 = rf(ctx, userID, key, value)
	} else {
		r0 = ret.Get(0).(string)
	}

	if rf, ok := ret.Get(1).(func(context.Context, string, string, string) error); ok {
		r1 = rf(ctx, userID, key, value)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// StorageRepo_Set_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Set'
type StorageRepo_Set_Call struct {
	*mock.Call
}

// Set is a helper method to define mock.On call
//   - ctx context.Context
//   - userID string
//   - key string
//   - value string
func (_e *StorageRepo_Expecter) Set(ctx interface{}, userID interface{}, key interface{}, value interface{}) *StorageRepo_Set_Call {
	return &StorageRepo_Set_Call{Call: _e.mock.On("Set", ctx, userID, key, value)}
}

func (_c *StorageRepo_Set_Call) Run(run func(ctx context.Context, userID string, key string, value string)) *StorageRepo_Set_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string), args[2].(string), args[3].(string))
	})
	return _c
}

func (_c *StorageRepo_Set_Call) Return(_a0 string, _a1 error) *StorageRepo_Set_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *StorageRepo_Set_Call) RunAndReturn(run func(context.Context, string, string, string) (string, error)) *StorageRepo_Set_Call {
	_c.Call.Return(run)
	return _c
}

// NewStorageRepo creates a new instance of StorageRepo. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewStorageRepo(t interface {
	mock.TestingT
	Cleanup(func())
}) *StorageRepo {
	mock := &StorageRepo{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
